import { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Fresh Apples',
    nameAr: 'تفاح طازج',
    description: 'Premium quality fresh apples imported from the best farms',
    descriptionAr: 'تفاح طازج بجودة ممتازة مستورد من أفضل المزارع',
    price: 2.5,
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400',
    category: 'Fruits',
    categoryAr: 'فواكه',
    unit: 'kg',
    unitAr: 'كجم',
    units: [
      { name: 'kg', nameAr: 'كجم', price: 2.5 },
      { name: 'box', nameAr: 'صندوق', price: 4.0 },
    ],
    stock: 50,
    discount: 10,
  },
  {
    id: '2',
    name: 'Bananas',
    nameAr: 'موز',
    description: 'Fresh tropical bananas rich in potassium',
    descriptionAr: 'موز استوائي طازج غني بالبوتاسيوم',
    price: 1.8,
    image: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400',
    category: 'Fruits',
    categoryAr: 'فواكه',
    unit: 'kg',
    unitAr: 'كجم',
    units: [
      { name: 'kg', nameAr: 'كجم', price: 1.8 },
      { name: 'bundle', nameAr: 'ربطة', price: 0.9 },
    ],
    stock: 100,
  },
  {
    id: '3',
    name: 'Strawberries',
    nameAr: 'فراولة',
    description: 'Sweet and juicy fresh strawberries',
    descriptionAr: 'فراولة طازجة حلوة وعصيرية',
    price: 4.5,
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
    category: 'Berries',
    categoryAr: 'توت',
    unit: 'box',
    unitAr: 'صندوق',
    units: [
      { name: 'box', nameAr: 'صندوق', price: 4.5 },
      { name: 'pack', nameAr: 'عبوة', price: 2.5 },
    ],
    stock: 30,
    discount: 15,
  },
  {
    id: '4',
    name: 'Oranges',
    nameAr: 'برتقال',
    description: 'Juicy oranges packed with vitamin C',
    descriptionAr: 'برتقال عصيري غني بفيتامين سي',
    price: 2.0,
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400',
    category: 'Citrus',
    categoryAr: 'حمضيات',
    unit: 'kg',
    unitAr: 'كجم',
    units: [
      { name: 'kg', nameAr: 'كجم', price: 2.0 },
      { name: 'bag', nameAr: 'كيس', price: 3.5 },
    ],
    stock: 75,
  },
  {
    id: '5',
    name: 'Mangoes',
    nameAr: 'مانجو',
    description: 'Sweet tropical mangoes from India',
    descriptionAr: 'مانجو استوائية حلوة من الهند',
    price: 3.5,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400',
    category: 'Tropical',
    categoryAr: 'استوائية',
    unit: 'kg',
    unitAr: 'كجم',
    units: [
      { name: 'kg', nameAr: 'كجم', price: 3.5 },
      { name: 'box', nameAr: 'صندوق', price: 5.5 },
    ],
    stock: 40,
    discount: 20,
  },
  {
    id: '6',
    name: 'Watermelon',
    nameAr: 'بطيخ',
    description: 'Refreshing and hydrating summer fruit',
    descriptionAr: 'فاكهة صيفية منعشة ومرطبة',
    price: 1.5,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784090?w=400',
    category: 'Melons',
    categoryAr: 'بطيخ',
    unit: 'piece',
    unitAr: 'حبة',
    units: [
      { name: 'piece', nameAr: 'حبة', price: 1.5 },
      { name: 'half', nameAr: 'نصف', price: 0.9 },
    ],
    stock: 20,
  },
  {
    id: '7',
    name: 'Grapes',
    nameAr: 'عنب',
    description: 'Seedless red grapes, perfect for snacking',
    descriptionAr: 'عنب أحمر بدون بذور، مثالي للتسلية',
    price: 3.0,
    image: 'https://images.unsplash.com/photo-1599819177795-d0eb4825d1d5?w=400',
    category: 'Berries',
    categoryAr: 'توت',
    unit: 'kg',
    unitAr: 'كجم',
    units: [
      { name: 'kg', nameAr: 'كجم', price: 3.0 },
      { name: 'box', nameAr: 'صندوق', price: 4.8 },
    ],
    stock: 60,
  },
  {
    id: '8',
    name: 'Pineapple',
    nameAr: 'أناناس',
    description: 'Fresh tropical pineapple with sweet taste',
    descriptionAr: 'أناناس استوائي طازج بطعم حلو',
    price: 2.8,
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400',
    category: 'Tropical',
    categoryAr: 'استوائية',
    unit: 'piece',
    unitAr: 'حبة',
    units: [
      { name: 'piece', nameAr: 'حبة', price: 2.8 },
      { name: 'half', nameAr: 'نصف', price: 1.6 },
    ],
    stock: 25,
  },
];

export const CATEGORIES = [
  { id: '1', name: 'Fruits', nameAr: 'فواكه', icon: '🍎' },
  { id: '2', name: 'Vegetables', nameAr: 'خضروات', icon: '🥕' },
  { id: '3', name: 'Berries', nameAr: 'توت', icon: '🍓' },
  { id: '4', name: 'Citrus', nameAr: 'حمضيات', icon: '🍊' },
  { id: '5', name: 'Tropical', nameAr: 'استوائية', icon: '🥭' },
  { id: '6', name: 'Melons', nameAr: 'بطيخ', icon: '🍉' },
];
